- name: clone dotfiles repo
  shell: "ghq get https://github.com/{{ dotfiles.ghuser }}/{{ dotfiles.repo }}.git"
  tags: dotfiles-clone

- name: deploy each symlink of dotfiles into $HOME
  command: ./install
  args:
    chdir: "~/ghq/github.com/{{ dotfiles.ghuser }}/{{ dotfiles.repo }}"
  tags: dotfiles-symlink
