homebrew:
  taps:
    - homebrew/cask
    - homebrew/cask-versions
    - homebrew/cask-fonts
    - homebrew/core
  casks:
    - android-studio
    - docker
    - google-cloud-sdk
    - google-chrome
    - google-japanese-ime
    - istat-menus
    - iterm2
    - ngrok
    - postman
    - slack
    - spectacle
    - visual-studio-code
